### PR TITLE
fix: add ga4

### LINKED ISSUE #219: Manglende sporing
Det virker som at sporingskoden ikke lastes inn på hovedsiden
på datafabrikken.norge.no når man lander på nettstedet. Den
lastes heller ikke inn på seksjonssidene "Om Datafabrikken",
"Siste nytt", "Kurs", "Veiledning".
Det er først når man går til seksjonssidene som f.eks. "Finn
data" eller "Datalandsbyen" at sporingskoden lastes inn.
Når sporingskoden først er lastet inn, spores sidevisninger på
alle sider gjennom allminnelig navigasjon, slik som via menylenker og brødsmulestien.
Sporingskoden forsvinner dersom man laster nettstedet inn på
nytt, noe som også skjer når man går til hovedsiden via lenken
oppe til venstre.

TILTAK:
Se på de ulike templates og implementere sporingskoden der
den mangler, slik at den lastes inn på alle sider.

### PR DESCRIPTION
**Pull request by jeffreiffers**
Fixes https://github.com/datadeling/datafabrikken-portal/issues/219

### CODE REVIEW

File: src/utils/analytics/index.ts [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+const registerPageViews = () => {
+  registerPageView();
+
+  Router.events.on('routeChangeComplete', () => {
+    registerPageView();
+  });
+};
+
+export const initAnalytics = () => {
+  if (!ReactGA.isInitialized && window) {
```
Comment (oyvindis) [inline src/utils/analytics/index.ts]: Bør kanskje bruke:
typeof window !== 'undefined'

**Review by oyvindis — DISMISSED** [review]

**Review by oyvindis — DISMISSED** [review]

**Review by oyvindis — DISMISSED** [review]

**Review by oyvindis — APPROVED** [review]

**Review by pooriamehregan — APPROVED** [review]
